# Generated by Django 3.0.6 on 2020-05-29 11:53

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planid', models.CharField(default=0, max_length=256)),
                ('planno', models.CharField(default=0, max_length=256)),
                ('parcelno', models.CharField(default=0, max_length=256)),
                ('coords', djgeojson.fields.PolygonField()),
                ('lat', models.CharField(default=0, max_length=256)),
                ('long', models.CharField(default=0, max_length=256)),
                ('area', models.CharField(default=0, max_length=256)),
            ],
        ),
    ]
