# Generated by Django 3.0.6 on 2020-05-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_auto_20200529_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelinfo',
            old_name='coords',
            new_name='geom',
        ),
    ]
