# Generated by Django 3.0 on 2020-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_auto_20200604_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelinfo',
            old_name='planid',
            new_name='parcelid',
        ),
        migrations.AddField(
            model_name='history',
            name='neighborhood',
            field=models.CharField(default='x', max_length=256),
            preserve_default=False,
        ),
    ]
