# Generated by Django 3.0 on 2020-06-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_auto_20200613_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='price_perm2',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
