# Generated by Django 3.0 on 2020-06-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_history_price_perm2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='price_perm2',
        ),
    ]
