# Generated by Django 3.0 on 2020-06-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0010_remove_history_price_perm2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='planid',
            new_name='parcelid',
        ),
    ]
